### ISSUE TITLE
本地开发项目启动后对话一直提示404 <!DOCTYPE html><html lang="zh"><head><meta charSet="utf-8"/>

### ISSUE THREAD

**Issue by pan-common** [labring/FastGPT#1403]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7.1

**问题描述, 日志截图**
其他功能正常,对话时报404错误,会弹出一个红色的错误提示框
**复现步骤**
创建应用,开始对话
**预期结果**
正常对话
**相关截图**
<img width="1214" alt="image" src="https://github.com/labring/FastGPT/assets/31590260/fd812039-58f7-4a62-b02b-890a272b42b7">

**Comment by pan-common** [comment]
已解决,.env.local 里的OPENAI_BASE_URL=http://127.0.0.1:3000/v1 配置改为OPENAI_BASE_URL=http://127.0.0.1:3001/v1 .奇怪的点是报错信息不太明确,连不上oneapi就说提示连不上,报了这么个错实在难定位
